name: 'Hello JS Action'
description: 'Une action GitHub locale JavaScript de démonstration.'
inputs:
  username:
    description: 'Nom de l’utilisateur à saluer'
    required: true
  greeting:
    description: 'Message de salutation'
    required: true
outputs:
  message:
    description: 'Message de salutation généré'
runs:
  using: 'node20'
  main: 'index.js'