name: Hello Template

on:
  workflow_call:
    inputs:
      username:
        description: "Nom de la personne à saluer"
        required: true
        type: string
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Saluer l'utilisateur
        run: echo "Bonjour, ${{ inputs.username }}  from reusable workflow!"